version: '3'
services:
  db:
    image: postgres:12
  dbsetup:
    build:
      context: ./
      dockerfile: ./DatabaseSetupDockerfile
    depends_on:
      - db
  webserver:
    build:
      context: ./
      dockerfile: ./WebServerDockerfile
    ports:
      - "5000:80"
    depends_on:
      - dbsetup